version: "3.9"
services:
  api:
    container_name: "api"
    build:
      dockerfile: ./StudentAdminPortal.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5033
    ports:
      - "5033:5033"
    depends_on:
      - db
    networks:
      - backend
  db:
    container_name: "db"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
networks:
  backend:
    driver: bridge